name: "Feature Request"
description: File a request for a new feature
labels: [ 'kind/feature', 'triage/needs-triage' ]
title: ''
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Request
      placeholder: |
        Before creating a new feature request please search for any existing related [issues](https://github.com/vmware-tanzu/community-edition/issues?q=is%3Aissue+). If you find an issue, join the discussion and add emoji or comments with your scenario or subscribe to follow updates
      description: |
        Provide details on the feature request here. Is your feature request relating to fixing a bug or is it to add/remove capabilities? Please describe what you would like to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        What other alternatives are there and why did you not choose them?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Screenshots or additional information and context
      description: |
        If screenshots or snippets can be provided, please do so here. Otherwise please add additional context if necessary.
  - type: markdown
    attributes:
      value: "## Environment Details"
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: |
        Please Select Appropriate Deployment Type Where This feature can be applicable
      multiple: true
      options:
        - Managed Cluster
        - Unmanaged Cluster
    validations:
      required: true
  - type: dropdown
    id: infrastructure
    attributes:
      label: Infrastructure provider
      description: |
        Please Select Infrastructure Provider. Where This feature can be applicable
      multiple: true
      options:
        - AWS
        - Azure
        - Docker
        - vSphere
    validations:
      required: true